### ISSUE TITLE
Export typeof `Action`

### ISSUE THREAD

**Issue by AnnaCate** [tnez/actions#42]
For testing and mocking, I'm running into some type issues that I _think_ would be resolved if I could have access to the type that corresponds to the `Action` class.

Edit: I'm playing around with the `ReturnType` utility and may be able to solve my problem with that. TBD/TBA

**Comment by tnez** [comment]
A screenshot of the problem being described:

![Screenshot 2023-07-12 at 10 08 07 AM](https://github.com/tnez/actions/assets/65454/20b40e67-8b06-410e-8310-cefceff1fd39)

Need better DX around passing in actions to other actions. Examples around this would be helpful both for documentation as well as validation.
